//Variable is like a labelled jar where you can store different things, just like using a jar to keep marbles or candies. The label helps you find and use what's inside, and you can change what you put in the jar anytime, like swapping candies for marbles. In programming, variables work the same way, holding and organizing data for your computer programs.

//Variables
var name = 'Sam'
console.log(name)

var y = 10;
console.log(y)

//Identifiers
//Just like you have a name to identify yourself, variables have identifiers to uniquely identify and refer to the data they hold. 
// All JavaScript variables must be identified with unique names.
// Names can contain letters, digits, underscores, and dollar signs.
// Names must begin with a letter
// Names can also begin with $ and _ 
// Names are case sensitive (y and Y are different variables)
// Reserved words (like JavaScript keywords) cannot be used as names



//Assignment Operator
// In JavScript, the assignment operator (=) is used to assign values to variables.
// To assign a value to a variable, write the variable name, followed by the assignment operator (=), followed by the value you want to assign to the variable.


// Declare a variable 'x' and set its value to 5.
var x = 5;

// Update the value of 'x' to 10.
x = 10;

// Print the updated value of 'x' to the console.
console.log(x);
